name: Playwright CI Base

on:
  workflow_dispatch:
    inputs:
      total_batches:
        description: 'Total number of batches'
        required: true
        default: '150'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Generate matrix
        run: |
          node generate-matrix.js ${{ github.event.inputs.total_batches }}
          echo "::set-output name=matrix::$(cat matrix.json)"
        id: set-matrix

  test:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        batch: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Cache node modules
        id: cache_node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Cache Playwright
        id: cache-playwright
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright
          restore-keys: |
            ${{ runner.os }}-playwright

      - name: Install Playwright
        run: npx playwright install

      - name: Split invoices
        run: npm run split

      - name: Run tests
        run: npm run test 
        env:
          INVOICE_BATCH_FILE: ${{ matrix.batch }}
        if: ${{ !cancelled() }}
